# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

            - name: Setup Dart SDK
  # You may pin to the exact commit or the version.
  # uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30
  uses: dart-lang/setup-dart@v1.6.4
  with:
    # This can be either the channel to install (i.e., 'stable', 'beta', 'dev'), an SDK release version (i.e., '2.19', '3.1'), or a specific SDK version (i.e, '2.19.1', '3.0.0-1.4.beta').
    sdk: # optional, default is stable
    # The CPU architecture ('x64', 'ia32', 'arm', or 'arm64').
    architecture: # optional
    # The build flavor ('release' or 'raw').
    flavor: # optional
          
     
